name: sc_bindings_vkb
dependencies:
  - python=3.12
  - xmltodict
  - pydantic
  - datamodel-code-generator
  - pip
  - pip:
    - pyqt6
    - git+https://gitlab.com/scmodding/frameworks/scdatatools.git

