name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Include test steps as in `test.yml`

  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
      # Include Windows build steps

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Include Linux build steps

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      # Include release steps
