name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      uses: test.yml

  build:
    needs: test
    runs-on: windows-latest
    steps:
      uses: build.yml

