name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./test.yml

  build:
    needs: test
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - name: Run build
        uses: ./build.yml