name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    uses: test.yml

  build:
    needs: test
    runs-on: [ubuntu-latest, windows-latest]
    uses: build.yml