name: CI
on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: test.yml

  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: build.yml

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: build.yml